### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by Shady-Abdelaziz** [mchengny/RWF2000-Video-Database-for-Violence-Detection#13]
when i try to run pre-trained mdel i got error in load_model

Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\Violence_Video_Detection-ML--main\predict_violence.py", line 19, in <module>
    model = load_model('keras_model.h5')
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\keras\utils\generic_utils.py", line 793, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by huhm** [comment]
I've this problem too. Have you fixed this problem ?

**Comment by huhm** [comment]
I‘m using the python 3.9.12
